export const SHOW_SIDEBAR = 'SHOW_SIDEBAR';
export const SET_USERNAME = 'SET_USERNAME';
export const SET_LOGIN = 'SET_LOGIN';

export const CATEGORIES_FETCH_DATA_SUCCESS = 'CATEGORIES_FETCH_DATA_SUCCESS';
export const CATEGORIES_HAS_ERRORED = 'CATEGORIES_HAS_ERRORED';
export const CATEGORIES_IS_LOADING = 'CATEGORIES_IS_LOADING';

export const OWNUSER_FETCH_DATA_SUCCESS = 'OWNUSER_FETCH_DATA_SUCCESS';
export const OWNUSER_HAS_ERRORED = 'OWNUSER_HAS_ERRORED';
export const OWNUSER_IS_LOADING = 'OWNUSER_IS_LOADING';

export const NOTIFICATIONS_FETCH_DATA_SUCCESS = 'NOTIFICATIONS_FETCH_DATA_SUCCESS';
export const NOTIFICATIONS_HAS_ERRORED = 'NOTIFICATIONS_HAS_ERRORED';
export const NOTIFICATIONS_IS_LOADING = 'NOTIFICATIONS_IS_LOADING';

export const CHATS_FETCH_DATA_SUCCESS = 'CHATS_FETCH_DATA_SUCCESS';
export const CHATS_HAS_ERRORED = 'CHATS_HAS_ERRORED';
export const CHATS_IS_LOADING = 'CHATS_IS_LOADING';

export const HOME_FETCH_DATA_SUCCESS = 'HOME_FETCH_DATA_SUCCESS';
export const HOME_HAS_ERRORED = 'HOME_HAS_ERRORED';
export const HOME_IS_LOADING = 'HOME_IS_LOADING';
