export const SHOW_SIDEBAR = 'SHOW_SIDEBAR';
export const CATEGORIES_HAS_ERRORED = 'CATEGORIES_HAS_ERRORED';
export const CATEGORIES_IS_LOADING = 'CATEGORIES_IS_LOADING';
export const CATEGORIES_FETCH_DATA_SUCCESS = 'CATEGORIES_FETCH_DATA_SUCCESS';
