export const SHOW_SIDEBAR = 'SHOW_SIDEBAR';
export const SET_USERNAME = 'SET_USERNAME';
export const SET_LOGIN = 'SET_LOGIN';

export const CATEGORIES_FETCH_DATA_SUCCESS = 'CATEGORIES_FETCH_DATA_SUCCESS';
export const CATEGORIES_HAS_ERRORED = 'CATEGORIES_HAS_ERRORED';
export const CATEGORIES_IS_LOADING = 'CATEGORIES_IS_LOADING';
export const OWNUSER_FETCH_DATA_SUCCESS = 'OWNUSER_FETCH_DATA_SUCCESS';
export const OWNUSER_HAS_ERRORED = 'OWNUSER_HAS_ERRORED';
export const OWNUSER_IS_LOADING = 'OWNUSER_IS_LOADING';
